### ISSUE TITLE
shortlist required

### ISSUE THREAD

**Issue by jorgtied** [XapaJIaMnu/translateLocally#82] opened 2022-01-18 15:27 UTC
It looks like that models without lexical shortlists do not load anymore.
There is a popup message "No path ro shortlist file is given".

I have no shortlist item in my config file.
Is there a problem in Options::hasAndNotEmpty of the bergamot-translator backend?

**Comment by jelmervdl** [comment] 2022-01-18 15:35
Hmm, that's likely caused by us using loading from memory bundles since https://github.com/XapaJIaMnu/translateLocally/commit/e573bb743ec372335c7f8ff079217a8e62032985. That assumes there is a shortlist to load as well.

[marian::bergamot::TranslationModel](https://github.com/browsermt/bergamot-translator/blob/13c55e2693d291078087de6e70f6773bb39cc415/src/translator/translation_model.cpp#L30) seems to still support models without shortlist. It is just [marian::begamot::getMemoryBundleFromConfig](https://github.com/browsermt/bergamot-translator/blob/13c55e2693d291078087de6e70f6773bb39cc415/src/translator/byte_array_util.cpp#L143) that doesn't.

Probably best to get this fixed in bergamot-translator.

**Closed** 2022-01-19 17:44 UTC
Labels: bug, upstream, regression
