### ISSUE TITLE
Persist settings

### ISSUE THREAD

**Issue by XapaJIaMnu** [XapaJIaMnu/translateLocally#23] opened 2021-05-12 17:56 UTC
We should persist the settings on relaunch. Load the same model that we had (if it exists), same number of cores, same memory, same input/output text (controllable by the settings dialog)

**Comment by XapaJIaMnu** [comment] 2021-05-19 16:23
Yeah, some of that was quite hacky... The point I was going for is that if we have everything in QSettings, then saving and loading is going to be very easy, but I didn't develop it much.

**Comment by jelmervdl** [comment] 2021-05-19 16:26
I thought it would be easy this way, but discovered that while QtQuick and Qt6 have bidirectional property binding, in Qt5/C++ you have to do it manually 😞 So you still end up writing a bunch of `connect()`s just to keep it all in sync.

**Comment by XapaJIaMnu** [comment] 2021-05-19 23:12
Shame....

**Comment by XapaJIaMnu** [comment] 2021-05-20 23:19
We do have persistent settings now, but...
If you wipe the models, and try to start translating, you would be greeted with a confusing error message that "you need to download models before you start translating". This is due to the settings attempting to restore the typed in text.

Furthermore, we should allow the user to wipe all typed in text on exit, to prevent some embarassing start up screens.

**Comment by jelmervdl** [comment] 2021-05-21 10:32
I'll fix the first error by not triggering translation on start-up (basically block the textChanged signal caused by restoring input text.)

This also saves users from triggering a large translate job on start-up. I can imagine a scenario where you trigger translation, then realise this is taking too long, try to close the program. Then, after the program finally closed (because you didn't force-close it or anything) and you open it again, it restores that long text and begins translating! Ugh.

Re "allow the user to wipe all typed in text on exit" should this
1. just be a checkbox in the settings pane that lets you turn on/off remembering the last input text?
2. Or a separate menu option to quit the program and forget the input text.
3. Could be a combination of both. Have a setting for default behaviour, and still have a menu item to trigger the other behaviour. This is pretty common in document-based macOS apps (e.g. Pages) that remember your open windows when you quit them. There's a global preference in macOS that tells apps they should remember their last open application state. With alt + cmd + q you override this behaviour when closing an app.

One more consideration: should this clear option overwrite the last saved text with nothing, or leave it untouched? I think clearing it makes more sense.

**Comment by kpu** [comment] 2021-05-21 10:34
For a privacy-focused product, I think it's really off-brand to be storing text translated on disk.  In my opinion, empty should be the default.

**Comment by jelmervdl** [comment] 2021-05-21 10:42
Hmm, that's true.

The main use case of remembering input text for me would be "oh shit I pressed the wrong key now the application quit and all my text is lost". But how many people will do their editing inside the translate app? For others it might be "I want to test out different models and not copy/paste my test text all the time." But that also doesn't seem to be the main use case. (and maybe we should just have an "Open file…" option anyway)

How much does optionally remembering input make sense in the context of this app? Should we just not store it at all and avoid confusion? I doubt many will mis it.

**Comment by XapaJIaMnu** [comment] 2021-05-21 10:53
I think a default off would be good here

**Comment by jelmervdl** [comment] 2021-05-21 10:59
I'll add a setting and turn it off by default. If off, it will not store (and effectively wipe) any input text on close.

**Comment by XapaJIaMnu** [comment] 2021-05-21 11:17
now, I have the text remembered, but it doesn't trigger translation, I think that's the "accidental usecase" right. But it looks weird, because the user has to type something to trigger the translation, unless the "translate as I type wasn't enabled".

**Comment by XapaJIaMnu** [comment] 2021-05-21 11:32
After couple of implementations I think this functionality can be removed. Adds more confusion than usefulness IMO ; (

**Comment by jelmervdl** [comment] 2021-05-21 11:41
I agree with @XapaJIaMnu. Too complicated to get right for the value it adds.

**Closed by jelmervdl** 2021-05-21 11:41 UTC
